---
# yamllint disable rule:line-length
name: pre-commit

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '**'

permissions: read-all

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install pre-commit dependencies
        run: |
          mkdir -p "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          # Install ShellCheck
          sudo apt install shellcheck

          # Install shfmt
          SHFFMT_VERSION="$(curl -sfSL https://api.github.com/repos/mvdan/sh/releases/latest | jq -r '.tag_name')"
          curl -sfSLo ./shfmt "https://github.com/mvdan/sh/releases/download/$SHFFMT_VERSION/shfmt_${SHFFMT_VERSION}_$(uname)_amd64"
          chmod +x shfmt
          mv shfmt $HOME/.local/bin/

          # Install golangci-lint
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - uses: pre-commit/action@v3.0.1